name: Test and Create the Wishlist
on: [push]
jobs:
  test_generate_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: |
          bundle exec rake
          bundle exec rake generate_wishlist
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add wishlist.txt
          git commit -m "Publishing latest wishlist"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
